# Generated by Django 5.2.5 on 2025-08-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='audio',
        ),
    ]
